### ISSUE TITLE
Support for ddc.vim v3.0.0

### ISSUE THREAD

**Issue by andi1984** [delphinus/ddc-treesitter#4]
Hi,

sorry, I'm not capable of saying what needs to be done to be compatible with the new DDC.vim v3, but it seems _some_ work is necessary as I get the message:

"Sources not found or don't support the ddc version" within vim.

Thus this should be more seen as a _note_ that ddc brought out a new major version and without further work it seems that ddc-sources might no longer be compatible which seems to hold true for this nice ddc source.

**Comment by andi1984** [comment]
https://github.com/Shougo/ddc.vim/releases/tag/v3.0.0

**Comment by delphinus** [comment]
Fixed by #5
